/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gems.ic.uff.br.view;

import gems.ic.uff.br.Exception.LcsXMLFilesException;
import gems.ic.uff.br.modelo.LcsXMLFiles;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gmenezes
 */
public class SimilarityDiff extends javax.swing.JFrame {

    /**
     * Creates new form SimilarityDiff
     */
    String directoryPath;
    JFrame diffFrame;
    JPanel diffPanel;
    LcsXMLFiles lcs;
    DrawSimilarityGraph dsg;

    public SimilarityDiff() {
        initComponents();
        Image img = null;
        img = Toolkit.getDefaultToolkit().createImage("../newView/images/Phoenix.png");
        this.setIconImage(img);
        directoryPath = "";
        diffFrame = null;
        diffPanel = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsSimilarity = new javax.swing.JSlider();
        jpGraph = new javax.swing.JPanel();
        jlSimilarity = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOpen = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsSimilarity.setBorder(javax.swing.BorderFactory.createTitledBorder("Similarity"));
        jsSimilarity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                similarityChange(evt);
            }
        });

        javax.swing.GroupLayout jpGraphLayout = new javax.swing.GroupLayout(jpGraph);
        jpGraph.setLayout(jpGraphLayout);
        jpGraphLayout.setHorizontalGroup(
            jpGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpGraphLayout.setVerticalGroup(
            jpGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jlSimilarity.setText("jLabel1");

        jmOpen.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmOpen.add(jMenuItem1);

        jMenuBar1.add(jmOpen);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jsSimilarity, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSimilarity)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jsSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jlSimilarity)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        JFileChooser caminho = new JFileChooser();
        caminho.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (caminho.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            directoryPath = caminho.getSelectedFile().toString();
        }

        try {

            lcs = new LcsXMLFiles(directoryPath);
            try {
                lcs.similarityDirectory();
            } catch (LcsXMLFilesException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                return;
            }

            
            
            
            dsg = new DrawSimilarityGraph();

            
            dsg.draw(lcs.getSimilarityMatrix(), lcs.getFiles(), Float.parseFloat((jsSimilarity.getValue() / 100.00) + ""));

            jpGraph.add(dsg.getVv());

            if (diffFrame == null) {
                diffFrame = new JFrame();
            }

            if (diffPanel == null) {
                diffPanel = new JPanel();
            }

            diffFrame.setSize(1000, 600);
            diffFrame.getContentPane().add(dsg.getVv());
            diffFrame.pack();
            diffFrame.setVisible(true);
            diffFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            jpGraph.removeAll();
            jpGraph.add(dsg.getVv());



        } catch (FileNotFoundException ex) {
            Logger.getLogger(SimilarityDiff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SimilarityDiff.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void similarityChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_similarityChange
        // TODO add your handling code here:
        jlSimilarity.setText(jsSimilarity.getValue() + "");

        if (!directoryPath.equals("")) {

            dsg = new DrawSimilarityGraph();
            dsg.draw(lcs.getSimilarityMatrix(), lcs.getFiles(), Float.parseFloat((jsSimilarity.getValue() / 100.00) + ""));

            jpGraph.removeAll();
            jpGraph.add(dsg.getVv());

            diffFrame.setSize(1000, 600);
            diffFrame.getContentPane().removeAll();
            diffFrame.getContentPane().add(dsg.getVv());
            diffFrame.pack();


        }
    }//GEN-LAST:event_similarityChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimilarityDiff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimilarityDiff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimilarityDiff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimilarityDiff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SimilarityDiff().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel jlSimilarity;
    private javax.swing.JMenu jmOpen;
    private javax.swing.JPanel jpGraph;
    private javax.swing.JSlider jsSimilarity;
    // End of variables declaration//GEN-END:variables
}
